name: todo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.7.0
  go_router: ^14.0.2
  floor: ^1.4.2
  fluttertoast: ^8.2.5
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/flutter.png"

flutter:
  uses-material-design: true
